### ISSUE TITLE
create a independent module problem.

### ISSUE THREAD

**Issue by zh1314** [qcadoo/mes#19]
i try to create a independent module according https://qcadoo.atlassian.net/wiki/spaces/QCDMESDOC/pages/3375264/How+to+create+an+independent+module document.
if i remove hook in model.xml, it will run successfully.
but when i add a hook , it will have problem in root.log file:

org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.qcadoo.mes.demo.hooks.ModelbHooks] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:296)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1127)
	at .........

source code:
model.xml:
\<hooks>
    \<onSave class="com.qcadoo.mes.demo.hooks.ModelbHooks" method="onSave" />
\</hooks>
ModelbHooks.java
package com.qcadoo.mes.demo.hooks;
import org.springframework.stereotype.Service;

import com.qcadoo.model.api.DataDefinition;
import com.qcadoo.model.api.Entity;
@Service
public class ModelbHooks {
	public void onSave(final DataDefinition companyDD, final Entity company) {
    }
}

what have i do wrong? please help me, thank you!

**Comment by zh1314** [comment]
i have found the solution:
i need to modify the root-context.xml  base-package="my service package path"
