### ISSUE TITLE
java.lang.IllegalStateException: Missing column: exportToPdfOnlyVisibleColumns in public.basic_parameter

### ISSUE THREAD

**Issue by guixiaorun** [qcadoo/mes#46]
java.lang.IllegalStateException: Missing column: exportToPdfOnlyVisibleColumns in public.basic_parameter
	at com.qcadoo.model.internal.sessionfactory.DynamicSessionFactoryBeanImpl.initialize(DynamicSessionFactoryBeanImpl.java:53)
	at com.qcadoo.model.internal.module.HibernateModuleFactory.postInit(HibernateModuleFactory.java:60)
	at com.qcadoo.plugin.internal.module.DefaultModuleFactoryAccessor.init(DefaultModuleFactoryAccessor.java:57)
	at com.qcadoo.plugin.internal.accessor.DefaultPluginAccessor.onApplicationEvent(DefaultPluginAccessor.java:215)
	at com.qcadoo.plugin.internal.accessor.DefaultPluginAccessor.onApplicationEvent(DefaultPluginAccessor.java:1)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:950)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4754)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5216)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)

**Comment by marcinperlak** [comment]
Hi - can you be more elaborate on this please?

**Comment by lponiewierski** [comment]
Hi,
update your schema version with:

`SELECT f_add_col_default('basic_parameter', 'exporttopdfonlyvisiblecolumns', 'boolean', 'false');`

or use updated from:

https://github.com/qcadoo/mes/tree/master/mes-application/src/main/resources/schema

Regards.
