### ISSUE TITLE
"Context initialization failed" occurs when trying to connect

### ISSUE THREAD

**Issue by wetpdyd** [qcadoo/mes#52]
After completing the installation with maven, we have completed the service startup with startup.sh. However, when attempting to connect, the following error is detected in the log. I would appreciate it if you could provide me with a solution.

Brought only error information

경고 -> WARN
심각 -> GRAVE

**catalina.2018-10-25.log**
`25-Oct-2018 14:25:00.085 경고 [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin [SetPropertiesRule]{Server/Service/Engine/Host} Setting property 'xmlValidation' to 'false' did not find a matching property.
25-Oct-2018 14:25:00.086 경고 [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin [SetPropertiesRule]{Server/Service/Engine/Host} Setting property 'xmlNamespaceAware' to 'false' did not find a matching property.
25-Oct-2018 14:25:47.961 심각 [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
25-Oct-2018 14:25:47.972 심각 [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
25-Oct-2018 14:25:48.185 경고 [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.`

**catalina.out**
`log4j:WARN No appenders could be found for logger (org.springframework.web.context.ContextLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[ParallelWebappClassLoader@14dc08cc] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
[ParallelWebappClassLoader@14dc08cc] warning no match for this type name: askForNotAcceptReason [Xlint:invalidAbsoluteTypeName]
[ParallelWebappClassLoader@14dc08cc] error at com/qcadoo/mes/techSubcontrForOperTasks/aop/OperationalTaskDetailsListenersOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.listeners.OperationalTaskDetailsListenersOTFO.setOperationalTaskNameAndDescription(..)) && args(BindingTypePattern(com.qcadoo.view.api.ViewDefinitionState, 1), BindingTypePattern(com.qcadoo.view.api.ComponentState, 2), BindingTypePattern(java.lang.String[], 3))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect.afterSetOperationalTaskNameAndDescriptionExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.view.api.ViewDefinitionState, com.qcadoo.view.api.ComponentState, java.lang.String[])))
[ParallelWebappClassLoader@14dc08cc] error at com/qcadoo/mes/techSubcontrForOperTasks/aop/OperationalTaskDetailsListenersOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.listeners.OperationalTaskDetailsListenersOTFO.setOperationalTaskNameAndDescription(..)) && args(BindingTypePattern(com.qcadoo.view.api.ViewDefinitionState, 1), BindingTypePattern(com.qcadoo.view.api.ComponentState, 2), BindingTypePattern(java.lang.String[], 3))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect.afterSetOperationalTaskNameAndDescriptionExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.view.api.ViewDefinitionState, com.qcadoo.view.api.ComponentState, java.lang.String[])))
[ParallelWebappClassLoader@14dc08cc] error at com/qcadoo/mes/techSubcontrForOperTasks/aop/OperationalTaskHooksOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.hooks.OperationalTaskHooksOTFO.onSave(..)) && args(BindingTypePattern(com.qcadoo.model.api.DataDefinition, 1), BindingTypePattern(com.qcadoo.model.api.Entity, 2))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect.afterOnSaveExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.model.api.DataDefinition, com.qcadoo.model.api.Entity)))
[ParallelWebappClassLoader@14dc08cc] error at com/qcadoo/mes/techSubcontrForOperTasks/aop/OperationalTaskHooksOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.hooks.OperationalTaskHooksOTFO.onSave(..)) && args(BindingTypePattern(com.qcadoo.model.api.DataDefinition, 1), BindingTypePattern(com.qcadoo.model.api.Entity, 2))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect.afterOnSaveExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.model.api.DataDefinition, com.qcadoo.model.api.Entity)))
[ParallelWebappClassLoader@14dc08cc] error aspect 'com.qcadoo.mes.productFlowThruDivision.warehouseIssue.states.aop.WarehouseIssueStateChangeAspect' woven into 'com.qcadoo.mes.productFlowThruDivision.warehouseIssue.states.aop.WarehouseIssueStateChangeAspect' must be defined to the weaver (placed on the aspectpath, or defined in an aop.xml file if using LTW).`

**localhost.2018-10-25.log**
`25-Oct-2018 14:25:47.960 심각 [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
 java.lang.NullPointerException: Cannot find model for ordersGroups.ordersGroup
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at com.qcadoo.model.internal.resolver.ModelXmlResolverImpl.addFields(ModelXmlResolverImpl.java:84)
	at com.qcadoo.model.internal.resolver.ModelXmlResolverImpl.getResources(ModelXmlResolverImpl.java:63)
	at com.qcadoo.model.internal.module.HibernateModuleFactory.postInit(HibernateModuleFactory.java:56)
	at com.qcadoo.plugin.internal.module.DefaultModuleFactoryAccessor.init(DefaultModuleFactoryAccessor.java:57)
	at com.qcadoo.plugin.internal.accessor.DefaultPluginAccessor.onApplicationEvent(DefaultPluginAccessor.java:215)
	at com.qcadoo.plugin.internal.accessor.DefaultPluginAccessor.onApplicationEvent(DefaultPluginAccessor.java:1)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:950)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4754)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5216)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

25-Oct-2018 14:25:47.975 정보 [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Closing Spring root WebApplicationContext
25-Oct-2018 14:25:48.182 정보 [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Shutting down log4j`

**root.log**
`com.qcadoo.plugin.internal.accessor.DefaultPluginAccessor - Plugin Framework initialized in 1319ms
2018-10-25 14:25:47,952 [localhost-startStop-1] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
java.lang.NullPointerException: Cannot find model for ordersGroups.ordersGroup
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at com.qcadoo.model.internal.resolver.ModelXmlResolverImpl.addFields(ModelXmlResolverImpl.java:84)
	at com.qcadoo.model.internal.resolver.ModelXmlResolverImpl.getResources(ModelXmlResolverImpl.java:63)
	at com.qcadoo.model.internal.module.HibernateModuleFactory.postInit(HibernateModuleFactory.java:56)
	at com.qcadoo.plugin.internal.module.DefaultModuleFactoryAccessor.init(DefaultModuleFactoryAccessor.java:57)
	at com.qcadoo.plugin.internal.accessor.DefaultPluginAccessor.onApplicationEvent(DefaultPluginAccessor.java:215)
	at com.qcadoo.plugin.internal.accessor.DefaultPluginAccessor.onApplicationEvent(DefaultPluginAccessor.java:1)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:950)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4754)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5216)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**warn.log**
`2018-10-25 14:25:47,952 [localhost-startStop-1] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
java.lang.NullPointerException: Cannot find model for ordersGroups.ordersGroup
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
	at com.qcadoo.model.internal.resolver.ModelXmlResolverImpl.addFields(ModelXmlResolverImpl.java:84)
	at com.qcadoo.model.internal.resolver.ModelXmlResolverImpl.getResources(ModelXmlResolverImpl.java:63)
	at com.qcadoo.model.internal.module.HibernateModuleFactory.postInit(HibernateModuleFactory.java:56)
	at com.qcadoo.plugin.internal.module.DefaultModuleFactoryAccessor.init(DefaultModuleFactoryAccessor.java:57)
	at com.qcadoo.plugin.internal.accessor.DefaultPluginAccessor.onApplicationEvent(DefaultPluginAccessor.java:215)
	at com.qcadoo.plugin.internal.accessor.DefaultPluginAccessor.onApplicationEvent(DefaultPluginAccessor.java:1)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:950)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4754)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5216)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-10-25 14:25:48,158 [localhost-startStop-1] WARN  org.springframework.beans.factory.support.DisposableBeanAdapter - Invocation of destroy method failed on bean with name 'sessionFactory': java.lang.NullPointerException`

**Comment by lponiewierski** [comment]
Hi,
this problem was fixes in new release.
Regards.
